### ISSUE TITLE
Group bugging out

### ISSUE THREAD

**Issue by lucaboox** [Project-Sloth/ps-playergroups#4]
If you create a group, then have someone make a group and then leave your group it glitches out and keeps your group but says you left it, so you can't create a new group unless you relog or restart the resource.

Here is an example of trying to create a group after it has happened 
![FiveM_b2372_GTAProcess_Tz3cyPjvyC](https://user-images.githubusercontent.com/11880505/173257880-f66c5092-abbb-4d5c-a8f7-4a1cea006164.png)

and here is the group list
![FiveM_b2372_GTAProcess_2NU8jS6yjg](https://user-images.githubusercontent.com/11880505/173257897-0a07755a-a833-48b4-ad13-660bb3f3dcc8.png)

**Comment by darktrovx** [comment]
Bug resolved in latest patch.

**Comment by trainordevs** [comment]
@devin-monro I seem to still be running into the issue.

https://i.imgur.com/Wf0JhUW.jpeg
