### ISSUE TITLE
Issues creating group after deleting one

### ISSUE THREAD

**Issue by boppescripting** [Project-Sloth/ps-playergroups#6]
There was a previous issue created for this problem (https://github.com/Project-Sloth/ps-playergroups/issues/4) that was closed and marked as completed but I am still having this issue.

Steps to reproduce:
(1) Create a group by yourself
(2) Have another player create a group
(3) Leave your group.
(4) Create another.
(5) Leave your group.
(6) Try to create another.

As with the previous issue, if I look at the available groups, it still shows that my group exists even though it has been deleted and I am no longer in it.

I know this seems like a fairly obscure problem, especially considering that you basically have to re-create your group a few times, but players like to find and cause issues. Once a players group is bugged, I often find myself having to restart the script, which causes players who are currently doing a group job to become completely screwed up until they fully relog.

This was tested on the most up-to-date version of the script after pulling a fresh copy from Github.

The below screenshot displays the notification you receive when trying to create another group.
https://i.imgur.com/Wf0JhUW.jpeg

**Comment by darktrovx** [comment]
Sorry for the late reply. Thought I pushed the fix for a few weeks back.
Just updated the code, I can not longer re-produce the error.
Let me know if you run into it again.

**Comment by boppescripting** [comment]
It seems fine on my local development box now. I am going to push this back to my live server and see if the issue still persists.

I'll keep you updated.

**Comment by boppescripting** [comment]
Had a couple players confirm that group jobs are now operational and they are not having the same issues with their groups. Thank you for the help.

If I run into anymore problems, I will create another issue!
